### ISSUE TITLE
WBCE 1.2 alpha-6: Installer error

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#149]
Install/save.php throws the following errors, so the installation can't be completed
Notice: A session had already been started - ignoring session_start() in /.../framework/classes/wbsession.php on line 54
Warning: Cannot modify header information - headers already sent by (output started at /.../framework/classes/wbsession.php:54) in /.../install/save.php on line 79

**Comment by NorHei** [comment]
i am on it

**Comment by NorHei** [comment]
0414c70

Fixed error , but now it does not store admin account , so still work to do . 
Please Point Stefanek to this as he has worked on Add_row DB method . 

Maybe he got an idea

**Comment by NorHei** [comment]
Hopefully fixed this now 
72f8cd7

Please test !

**Comment by NorHei** [comment]
Btw, the installer is pure horror , i hate this hing !!!

**Comment by instantflorian** [comment]
Sorry, still doesn't work properly

`Array ( [user_id] => 1 [group_id] => 1 [groups_id] => 1 [active] => 1 [username] => wbadmin [language] => DE [password] => 9529789715b8c88e3400d193772ae5ed [email] => aaa@bbb.tld [timezone] => 0 [display_name] => Administrator )
Notice: A session had already been started - ignoring session_start() in /.../framework/classes/wbsession.php on line 54

Array
(
    [0] => e28:Table 'AAA.BBB_mod_droplets' doesn't exist
)

Array
(
)


Warning: Cannot modify header information - headers already sent by (output started at /.../install/save.php:434) in /.../install/save.php on line 500
`

**Comment by instantflorian** [comment]
New errors


Warning: include_once(/.../config.php): failed to open stream: No such file or directory in /.../install/save.php on line 338

Warning: include_once(): Failed opening '/.../config.php' for inclusion (include_path='.:/opt/php/7.0.11/share/pear') in /.../install/save.php on line 338

Notice: Use of undefined constant ADMIN_DIRECTORY - assumed 'ADMIN_DIRECTORY' in /.../install/save.php on line 349

Notice: Use of undefined constant WB_URL - assumed 'WB_URL' in /.../install/save.php on line 350

Notice: Use of undefined constant ADMIN_DIRECTORY - assumed 'ADMIN_DIRECTORY' in /.../install/save.php on line 350

Warning: require(/.../ADMIN_DIRECTORY/interface/version.php): failed to open stream: No such file or directory in /.../install/save.php on line 351

Warning: require(/.../ADMIN_DIRECTORY/interface/version.php): failed to open stream: No such file or directory in /.../install/save.php on line 351

Fatal error: require(): Failed opening required '/.../ADMIN_DIRECTORY/interface/version.php' (include_path='.:/opt/php/7.0.11/share/pear') in /.../install/save.php on line 351
